const $=id=>document.getElementById(id);
const panels=["communicationPanel","scannerPanel","calculatorPanel","readerPanel"];
function showStatus(text){const e=$("status");if(e)e.textContent=text||"Ready"}
function setListening(active){const b=$("listenBtn"),t=$("listenText");if(b)b.classList.toggle("active",active);if(t)t.textContent=active?"Listening…":"Tap to speak";showStatus(active?"Listening…":"Ready")}
function addHistory(text){const list=$("historyList");if(!list)return;const empty=list.querySelector(".empty-history");if(empty)empty.remove();const item=document.createElement("div");item.className="history-item";const strong=document.createElement("strong");strong.textContent=text;const span=document.createElement("span");span.textContent=new Date().toLocaleTimeString("en-IN",{hour:"numeric",minute:"2-digit"});item.append(strong,span);list.prepend(item);while(list.children.length>8)list.lastElementChild.remove();try{const h=JSON.parse(localStorage.getItem("accessbridge_history")||"[]");h.unshift({text,time:Date.now()});localStorage.setItem("accessbridge_history",JSON.stringify(h.slice(0,8)))}catch(e){}}
function loadHistory(){try{const h=JSON.parse(localStorage.getItem("accessbridge_history")||"[]");const list=$("historyList");if(!list||!h.length)return;list.innerHTML="";h.forEach(x=>{const item=document.createElement("div");item.className="history-item";const strong=document.createElement("strong");strong.textContent=x.text;const span=document.createElement("span");span.textContent=new Date(x.time).toLocaleTimeString("en-IN",{hour:"numeric",minute:"2-digit"});item.append(strong,span);list.append(item)})}catch(e){}}
function hideAllPanels(){panels.forEach(id=>$(id)?.classList.add("hidden"))}
function openPanel(id){hideAllPanels();$(id)?.classList.remove("hidden");setTimeout(()=>$(id)?.scrollIntoView({behavior:"smooth",block:"start"}),50)}
function openCommunication(){openPanel("communicationPanel")}
function openScanner(){openPanel("scannerPanel")}
function openReader(){openPanel("readerPanel")}
function showCalculation(expression,result){openPanel("calculatorPanel");$("calculationInput").value=expression;$("calculationResult").textContent="Answer: "+result}
function calculateManual(){const input=$("calculationInput");if(!input)return;const result=AccessBridgeAI.calculate(input.value);if(result===null){$("calculationResult").textContent="I could not understand that calculation.";AccessBridgeAI.speak("I could not understand that calculation.")}else{$("calculationResult").textContent="Answer: "+result;AccessBridgeAI.speak("The answer is "+result)}}
function speakMessage(){const text=$("messageInput")?.value.trim();if(!text){AccessBridgeAI.speak("Please enter a message first.");return}AccessBridgeAI.speak(text)}
function startCaption(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){AccessBridgeAI.speak("Voice recognition is not supported in this browser.");return}const r=new R;r.lang="en-IN";r.continuous=false;r.interimResults=false;$("liveCaption").textContent="Listening…";r.onresult=e=>{$("liveCaption").textContent=e.results[0][0].transcript};r.onerror=()=>{$("liveCaption").textContent="Could not understand the voice.";AccessBridgeAI.speak("I could not understand that.")};r.onend=()=>{if($("liveCaption").textContent==="Listening…")$("liveCaption").textContent="Tap Listen to convert speech into text."};try{r.start()}catch(e){}}
function sendWhatsApp(){const text=$("messageInput")?.value.trim();if(!text){AccessBridgeAI.speak("Please type a message first.");return}let contact=null;const name=prompt("Enter saved contact name, or phone number:");if(!name)return;if(typeof findContact==="function"){try{contact=findContact(name)}catch(e){}}let phone="";if(contact){phone=contact.phone||contact.number||contact.mobile||""}else if(/^\+?\d[\d\s-]{7,}$/.test(name)){phone=name.replace(/[^\d+]/g,"")}if(!phone){AccessBridgeAI.speak("I could not find that contact.");alert("Contact not found. You can enter a phone number instead.");return}phone=phone.replace(/\D/g,"");if(phone.length===10)phone="91"+phone;const url="https://wa.me/"+phone+"?text="+encodeURIComponent(text);AccessBridgeAI.speak("Opening WhatsApp with your message.");window.open(url,"_blank")}
async function initCamera(){if(typeof startObjectCamera==="function"){await startObjectCamera()}else{AccessBridgeAI.speak("The object scanner is not available yet.")}}
async function scanObject(){if(typeof scanCurrentObject==="function"){await scanCurrentObject()}else{AccessBridgeAI.speak("The object scanner is not available yet.")}}
function stopCamera(){if(typeof stopObjectCamera==="function")stopObjectCamera()}
function clearMessage(){$("messageInput").value=""}
function clearHistory(){localStorage.removeItem("accessbridge_history");const list=$("historyList");if(list)list.innerHTML='<p class="empty-history">No recent activity.</p>'}
function setup(){loadHistory();$("listenBtn")?.addEventListener("click",()=>AccessBridgeAI.start());document.querySelectorAll(".action-card").forEach(b=>b.addEventListener("click",()=>AccessBridgeAI.handle(b.dataset.command||"")));$("calculatorBtn")?.addEventListener("click",()=>openPanel("calculatorPanel"));$("scannerBtn")?.addEventListener("click",openScanner);$("communicationBtn")?.addEventListener("click",openCommunication);$("readerBtn")?.addEventListener("click",openReader);$("calculateBtn")?.addEventListener("click",calculateManual);$("speakMessageBtn")?.addEventListener("click",speakMessage);$("clearMessageBtn")?.addEventListener("click",clearMessage);$("captionBtn")?.addEventListener("click",startCaption);$("sendMessageBtn")?.addEventListener("click",sendWhatsApp);$("startCameraBtn")?.addEventListener("click",initCamera);$("scanObjectBtn")?.addEventListener("click",scanObject);$("stopCameraBtn")?.addEventListener("click",stopCamera);$("readTextBtn")?.addEventListener("click",()=>{const text=$("readerInput")?.value.trim();if(!text){AccessBridgeAI.speak("Please enter some text first.");return}AccessBridgeAI.speak(text)});$("clearHistoryBtn")?.addEventListener("click",clearHistory);document.querySelectorAll("[data-close]").forEach(b=>b.addEventListener("click",()=>$(b.dataset.close)?.classList.add("hidden")));$("settingsBtn")?.addEventListener("click",()=>{if(typeof openSettings==="function")openSettings();else AccessBridgeAI.speak("Settings are available through the accessibility controls.")});}
document.addEventListener("DOMContentLoaded",setup);
window.showStatus=showStatus;
window.setListening=setListening;
window.addHistory=addHistory;
window.openCommunication=openCommunication;
window.openScanner=openScanner;
window.openReader=openReader;
window.showCalculation=showCalculation;